/**
 * Локализация названий стран (EN → RU).
 * Ключи — как приходят из TMDB (production_countries[].name, English).
 */
const countryNamesRu = {
  'United States of America': 'США',
  'United States': 'США',
  USA: 'США',
  'United Kingdom': 'Великобритания',
  UK: 'Великобритания',
  France: 'Франция',
  Germany: 'Германия',
  Japan: 'Япония',
  'South Korea': 'Южная Корея',
  India: 'Индия',
  Italy: 'Италия',
  Spain: 'Испания',
  China: 'Китай',
  'Hong Kong': 'Гонконг',
  Canada: 'Канада',
  Australia: 'Австралия',
  Russia: 'Россия',
  'Russian Federation': 'Россия',
  Brazil: 'Бразилия',
  Mexico: 'Мексика',
  Sweden: 'Швеция',
  Denmark: 'Дания',
  Norway: 'Норвегия',
  Finland: 'Финляндия',
  Poland: 'Польша',
  'Czech Republic': 'Чехия',
  'Czechia': 'Чехия',
  Hungary: 'Венгрия',
  Romania: 'Румыния',
  Greece: 'Греция',
  Turkey: 'Турция',
  Iran: 'Иран',
  Israel: 'Израиль',
  Egypt: 'Египет',
  'South Africa': 'ЮАР',
  Argentina: 'Аргентина',
  Chile: 'Чили',
  Colombia: 'Колумбия',
  Belgium: 'Бельгия',
  Netherlands: 'Нидерланды',
  Austria: 'Австрия',
  Switzerland: 'Швейцария',
  Ireland: 'Ирландия',
  'New Zealand': 'Новая Зеландия',
  Thailand: 'Таиланд',
  Indonesia: 'Индонезия',
  Vietnam: 'Вьетнам',
  Philippines: 'Филиппины',
  Malaysia: 'Малайзия',
  Singapore: 'Сингапур',
  Taiwan: 'Тайвань',
  Ukraine: 'Украина',
  Kazakhstan: 'Казахстан',
  Georgia: 'Грузия',
  Armenia: 'Армения',
  Azerbaijan: 'Азербайджан',
  Belarus: 'Беларусь',
  Portugal: 'Португалия',
  Croatia: 'Хорватия',
  Serbia: 'Сербия',
  Bulgaria: 'Болгария',
  Slovakia: 'Словакия',
  Slovenia: 'Словения',
  Estonia: 'Эстония',
  Latvia: 'Латвия',
  Lithuania: 'Литва',
  Iceland: 'Исландия',
  Luxembourg: 'Люксембург',
  Morocco: 'Марокко',
  Algeria: 'Алжир',
  Tunisia: 'Тунис',
  Nigeria: 'Нигерия',
  Kenya: 'Кения',
  Pakistan: 'Пакистан',
  Bangladesh: 'Бангладеш',
  'Sri Lanka': 'Шри-Ланка',
  Nepal: 'Непал',
  Afghanistan: 'Афганистан',
  Iraq: 'Ирак',
  Lebanon: 'Ливан',
  Syria: 'Сирия',
  Jordan: 'Иордания',
  'Saudi Arabia': 'Саудовская Аравия',
  'United Arab Emirates': 'ОАЭ',
  Qatar: 'Катар',
  Kuwait: 'Кувейт',
  Cuba: 'Куба',
  Venezuela: 'Венесуэла',
  Peru: 'Перу',
  Ecuador: 'Эквадор',
  Uruguay: 'Уругвай',
  Bolivia: 'Боливия',
  Paraguay: 'Парагвай',
  'Puerto Rico': 'Пуэрто-Рико',
  'Dominican Republic': 'Доминиканская Республика',
  Jamaica: 'Ямайка',
  'Trinidad and Tobago': 'Тринидад и Тобаго',
  'Soviet Union': 'СССР',
  'West Germany': 'ФРГ',
  'East Germany': 'ГДР',
  Yugoslavia: 'Югославия',
}

/**
 * @param {string} name — название страны (обычно на английском из TMDB)
 * @returns {string} — название на русском или исходное, если перевода нет
 */
export function getCountryNameRu(name) {
  if (!name || typeof name !== 'string') return ''
  const key = name.trim()
  return countryNamesRu[key] || name
}
